
//LWR_API 1.0

package org.luwrain.core;

public enum Hint
{
    BEGIN_OF_LINE,
    BEGIN_OF_TEXT,
    EMPTY_LINE,
    END_OF_LINE,
    END_OF_TEXT,
    LINE_BOUND,
    NO_CONTENT,
    NO_ITEMS_ABOVE,
    NO_ITEMS_BELOW,
    NO_LINES_ABOVE,
    NO_LINES_BELOW,
    SPACE,
    TAB,
    TABLE_BEGIN_OF_ROW,
    TABLE_END_OF_COL,
    TABLE_END_OF_ROW,
    TABLE_NO_ROWS_ABOVE,
    TABLE_NO_ROWS_BELOW,
    TREE_BEGIN,
    TREE_BRANCH_COLLAPSED,
    TREE_BRANCH_EXPANDED,
    TREE_END,
} 
